// styles/NivelGuaibaStyles.js
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 20,
  },
  header: {
    backgroundColor: '#1e40af',
    paddingVertical: 25,
    alignItems: 'center',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: 1,
  },
  nivelContainer: {
    alignItems: 'center',
    paddingVertical: 40,
    backgroundColor: '#f0f9ff',
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  waveEmoji: {
    fontSize: 40,
    marginBottom: 10,
  },
  nivel: {
    fontSize: 52,
    fontWeight: 'bold',
    color: '#1e40af',
    marginBottom: 8,
    textShadowColor: 'rgba(30, 64, 175, 0.2)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  timestamp: {
    fontSize: 16,
    color: '#64748b',
    fontStyle: 'italic',
  },
  infoContainer: {
    padding: 25,
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  infoText: {
    fontSize: 16,
    color: '#374151',
    marginBottom: 12,
    textAlign: 'center',
    lineHeight: 22,
  },
  separator: {
    height: 1,
    backgroundColor: '#e2e8f0',
    marginHorizontal: 20,
    marginVertical: 25,
  },
  footer: {
    padding: 25,
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    marginTop: 10,
  },
  footerText: {
    fontSize: 14,
    color: '#475569',
    textAlign: 'center',
    marginBottom: 6,
    lineHeight: 20,
  },
  version: {
    fontSize: 14,
    color: '#334155',
    fontWeight: '600',
    marginTop: 15,
    marginBottom: 12,
  },
  disclaimer: {
    fontSize: 12,
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 16,
    fontStyle: 'italic',
    marginTop: 5,
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#64748b',
    textAlign: 'center',
  },
});